//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by es_odbc.rc
//
#define IDS_BADDSN                      1
#define IDS_MSGTITLE                    2
#define IDS_ADVANCE_OPTION_DEF          3
#define IDOK2                           3
#define IDS_ADVANCE_SAVE                4
#define IDCANCEL2                       4
#define IDC_TEST                        4
#define IDC_PASSWORD_STATIC             4
#define IDC_SSL_STATIC                  4
#define IDS_ADVANCE_OPTION_DSN1         5
#define IDC_HOST_VER_STATIC             5
#define IDS_ADVANCE_OPTION_CON1         6
#define IDC_HOST_VER_STATIC2            6
#define IDS_ADVANCE_OPTION_DSN2         7
#define IDS_ADVANCE_OPTION_CON2         8
#define IDS_ADVANCE_CONNECTION          9
#define IDS_ADVANCE_OPTION_DSN3         10
#define KEEPALIVE_X                     10
#define DTC_GRP_X                       10
#define IDS_ADVANCE_OPTION_CON3         11
#define DTC_OPT_HEIGHT                  45
#define DTC_GRP_Y                       60
#define DTC_GRP_HEIGHT                  100
#define DLG_OPTIONS_DRV                 102
#define MISC_Y                          145
#define DTC_OPT_WIDTH                   180
#define CONNSETTINGS_Y                  185
#define LIBPQOPT_Y                      185
#define DTC_GRP_WIDTH                   200
#define KEEPALIVE_Y                     225
#define ENDLINE_Y                       245
#define IDC_DSNAME                      400
#define IDC_DSNAMETEXT                  401
#define IDC_DESC                        404
#define IDC_SERVER                      407
#define IDC_DATABASE                    408
#define IDC_SSLMODE                     409
#define IDC_SERVER2                     409
#define IDC_CERTIFICATE                 409
#define IDS_SSLREQUEST_PREFER           410
#define IDC_KEY                         410
#define IDS_SSLREQUEST_ALLOW            411
#define IDS_SSLREQUEST_REQUIRE          412
#define IDS_SSLREQUEST_DISABLE          413
#define IDC_NOTICE_USER                 414
#define IDS_SSLREQUEST_VERIFY_CA        415
#define IDS_SSLREQUEST_VERIFY_FULL      416
#define IDS_AUTHTYPE_NONE               417
#define IDS_AUTHTYPE_BASIC              418
#define IDS_AUTHTYPE_IAM                419
#define DLG_CONFIG                      1001
#define IDC_PORT                        1002
#define IDC_USER                        1006
#define IDC_PASSWORD                    1009
#define IDC_PASSWORD2                   1010
#define IDC_ACCESS_KEY                  1010
#define IDC_SECRETACCESS_KEY            1011
#define IDC_DATASOURCE                  1018
#define DRV_OPTIMIZER                   1019
#define IDC_DRIVER                      1021
#define DRV_CONNSETTINGS                1031
#define DRV_READONLY                    1037
#define IDC_DESCTEXT                    1039
#define DRV_MSG_LABEL                   1040
#define DRV_CANCELASFREESTMT            1053
#define IDC_OPTIONS                     1054
#define DRV_OR_DSN                      1059
#define DS_DISALLOWPREMATURE            1061
#define IDNEXTPAGE                      1065
#define IDPREVPAGE                      1066
#define DRV_MSG_LABEL2                  1073
#define IDC_DRIVERNAME                  1076
#define IDC_MANAGEDSN                   1077
#define DS_GSSAUTHUSEGSSAPI             1087
#define DS_DEFAULT_DTCLOG               1091
#define DS_DTCLOG                       1092
#define DS_NO_DTCLOG                    1093
#define DS_DTC_NO_USE                   1097
#define DS_NUMERIC_AS_NUMERIC           1108
#define IDC_EDIT1                       1112
#define IDC_CONNTIMEOUT_STATIC          1112
#define IDC_CHECK1                      1113
#define IDC_CHECK2                      1114
#define IDC_USESSL                      1114
#define IDC_COMBO1                      1115
#define IDC_AUTHTYPE                    1115
#define IDC_HOST_VER                    1115
#define IDC_USERNAME_STATIC             1116
#define IDC_CHECK4                      1117
#define IDC_ALLOWSELFSIGNED             1117
#define IDC_CERTIFICATE_STATIC          1118
#define IDC_RICHEDIT21                  1119
#define IDC_CERTIFICATE_STATIC2         1119
#define IDC_CERTIFICATENOTE_STATIC      1119
#define IDC_KEY_STATIC                  1119
#define IDC_MFCEDITBROWSE1              1120
#define IDC_REGION                      1121
#define IDC_REGION_STATIC               1122
#define IDC_AUTH_STATIC                 1123
#define ID_ADVANCED_OPTIONS             1124
#define ID_LOG_OPTIONS                  1125
#define IDC_DRIVER_VERSION              1126
#define IDC_AUTH_SETTINGS               1127
#define IDC_CONN_SETTINGS               1128
#define DLG_ADVANCED_OPTIONS            1129
#define IDC_EDIT2                       1130
#define IDC_CONNTIMEOUT                 1130

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1131
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
